name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.platform.os }}

    strategy:
      fail-fast: false
      matrix:
        platform:
          - { os: windows-latest }
          - { os: macos-latest }
          - { os: ubuntu-latest }
    steps:
    - uses: actions/checkout@v3
    - uses: './action.yml'

